// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PimpYourBlech_Data.Persistence.EFDatabase;

#nullable disable

namespace PimpYourBlech_Data.Migrations
{
    [DbContext(typeof(ConfiguratorContext))]
    [Migration("20260118212530_migrationpyb")]
    partial class migrationpyb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.HasSequence<int>("ArticleNumberSeq")
                .StartsAt(100000L);

            modelBuilder.Entity("ConfigurationProduct", b =>
                {
                    b.Property<int>("ConfigurationsId")
                        .HasColumnType("integer");

                    b.Property<int>("ProductsProductId")
                        .HasColumnType("integer");

                    b.HasKey("ConfigurationsId", "ProductsProductId");

                    b.HasIndex("ProductsProductId");

                    b.ToTable("ConfigurationProduct");
                });

            modelBuilder.Entity("PimpYourBlech_Data.Models.Car", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DatePermit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DateProduction")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PS")
                        .HasColumnType("integer");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Cars");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Brand = "Volkswagen",
                            DatePermit = "2026",
                            DateProduction = "2025",
                            Model = "GTI 2025",
                            Name = "Golf",
                            PS = 325,
                            Price = 45000m,
                            Quantity = 20
                        },
                        new
                        {
                            Id = 2,
                            Brand = "Volkswagen",
                            DatePermit = "2021",
                            DateProduction = "2020",
                            Model = "Polo 2020",
                            Name = "Polo",
                            PS = 225,
                            Price = 25000m,
                            Quantity = 15
                        });
                });

            modelBuilder.Entity("PimpYourBlech_Data.Models.ColorDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProductId")
                        .IsUnique();

                    b.ToTable("Colors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayName = "Tornadorot",
                            ProductId = 7
                        },
                        new
                        {
                            Id = 2,
                            DisplayName = "Metallic Weiß Perleffekt",
                            ProductId = 8
                        },
                        new
                        {
                            Id = 3,
                            DisplayName = "Deep Black Pearl",
                            ProductId = 17
                        },
                        new
                        {
                            Id = 4,
                            DisplayName = "Crystal Ice Blue Metallic",
                            ProductId = 9
                        },
                        new
                        {
                            Id = 5,
                            DisplayName = "Kings Red Velvet",
                            ProductId = 10
                        },
                        new
                        {
                            Id = 6,
                            DisplayName = "Urban Grey Metallic",
                            ProductId = 18
                        });
                });

            modelBuilder.Entity("PimpYourBlech_Data.Models.CommunityAnswer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int>("QuestionId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.ToTable("CommunityAnswers");
                });

            modelBuilder.Entity("PimpYourBlech_Data.Models.CommunityQuestion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("Id");

                    b.ToTable("CommunityQuestions");
                });

            modelBuilder.Entity("PimpYourBlech_Data.Models.Configuration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CarId")
                        .HasColumnType("integer");

                    b.Property<int>("CustomerId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CarId");

                    b.HasIndex("CustomerId");

                    b.ToTable("Configurations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CarId = 1,
                            CustomerId = 1,
                            Name = "Max' Golf Konfiguration"
                        },
                        new
                        {
                            Id = 2,
                            CarId = 2,
                            CustomerId = 1,
                            Name = "Max' Polo Konfiguration"
                        },
                        new
                        {
                            Id = 3,
                            CarId = 2,
                            CustomerId = 2,
                            Name = "Mustermann Polo Setup"
                        },
                        new
                        {
                            Id = 4,
                            CarId = 1,
                            CustomerId = 2,
                            Name = "Mustermann Golf Setup"
                        });
                });

            modelBuilder.Entity("PimpYourBlech_Data.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("AdminRights")
                        .HasColumnType("boolean");

                    b.Property<string>("FirstName")
                        .HasColumnType("text");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .HasColumnType("text");

                    b.Property<string>("MailAddress")
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Telefon")
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AdminRights = true,
                            FirstName = "Max",
                            ImagePath = "/CustomerImages/Car1.png",
                            LastName = "Mustermann",
                            MailAddress = "mustermail-admin.adresse@mustermail.de",
                            PasswordHash = "P6zbHsZ98YHkhf6yoM/EMMjAOt31qqUEdCRYJrKpKqs=",
                            Telefon = "0123456789",
                            Username = "MusterAdmin"
                        },
                        new
                        {
                            Id = 2,
                            AdminRights = false,
                            FirstName = "Max",
                            ImagePath = "/CustomerImages/Car1.png",
                            LastName = "Mustermann",
                            MailAddress = "mustermail.adresse@mustermail.de",
                            PasswordHash = "P6zbHsZ98YHkhf6yoM/EMMjAOt31qqUEdCRYJrKpKqs=",
                            Telefon = "0123456789",
                            Username = "MusterMax"
                        });
                });

            modelBuilder.Entity("PimpYourBlech_Data.Models.DeliveryAddress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("CustomerId")
                        .HasColumnType("integer");

                    b.Property<string>("HouseNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Lastname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Salutation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Town")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("DeliveryAddresses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Country = "DE",
                            CustomerId = 1,
                            HouseNumber = "12A",
                            Lastname = "Mustermann",
                            PostalCode = "83022",
                            Salutation = "Herr",
                            Street = "Musterstraße",
                            Surname = "Admin",
                            Town = "Rosenheim"
                        },
                        new
                        {
                            Id = 2,
                            Country = "DE",
                            CustomerId = 2,
                            HouseNumber = "12A",
                            Lastname = "Mustermann",
                            PostalCode = "83022",
                            Salutation = "Herr",
                            Street = "Musterstraße",
                            Surname = "Max",
                            Town = "Rosenheim"
                        });
                });

            modelBuilder.Entity("PimpYourBlech_Data.Models.EngineDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Displacement")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Fuel")
                        .HasColumnType("integer");

                    b.Property<int>("Gear")
                        .HasColumnType("integer");

                    b.Property<int>("Kw")
                        .HasColumnType("integer");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<int>("Ps")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProductId")
                        .IsUnique();

                    b.ToTable("Engines");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Displacement = "2.0",
                            Fuel = 0,
                            Gear = 2,
                            Kw = 239,
                            ProductId = 3,
                            Ps = 325
                        },
                        new
                        {
                            Id = 2,
                            Displacement = "2.0",
                            Fuel = 0,
                            Gear = 2,
                            Kw = 265,
                            ProductId = 4,
                            Ps = 360
                        },
                        new
                        {
                            Id = 3,
                            Displacement = "1.8",
                            Fuel = 3,
                            Gear = 2,
                            Kw = 210,
                            ProductId = 15,
                            Ps = 280
                        },
                        new
                        {
                            Id = 4,
                            Displacement = "1.0",
                            Fuel = 0,
                            Gear = 1,
                            Kw = 81,
                            ProductId = 11,
                            Ps = 110
                        },
                        new
                        {
                            Id = 5,
                            Displacement = "1.5",
                            Fuel = 0,
                            Gear = 2,
                            Kw = 110,
                            ProductId = 12,
                            Ps = 150
                        },
                        new
                        {
                            Id = 6,
                            Displacement = "1.2",
                            Fuel = 3,
                            Gear = 2,
                            Kw = 96,
                            ProductId = 19,
                            Ps = 130
                        });
                });

            modelBuilder.Entity("PimpYourBlech_Data.Models.LightsDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsLed")
                        .HasColumnType("boolean");

                    b.Property<int>("Lumen")
                        .HasColumnType("integer");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProductId")
                        .IsUnique();

                    b.ToTable("Lights");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsLed = true,
                            Lumen = 3200,
                            ProductId = 5
                        },
                        new
                        {
                            Id = 2,
                            IsLed = true,
                            Lumen = 3000,
                            ProductId = 6
                        },
                        new
                        {
                            Id = 3,
                            IsLed = true,
                            Lumen = 3800,
                            ProductId = 16
                        },
                        new
                        {
                            Id = 4,
                            IsLed = true,
                            Lumen = 2600,
                            ProductId = 13
                        },
                        new
                        {
                            Id = 5,
                            IsLed = true,
                            Lumen = 3100,
                            ProductId = 14
                        },
                        new
                        {
                            Id = 6,
                            IsLed = true,
                            Lumen = 3400,
                            ProductId = 20
                        });
                });

            modelBuilder.Entity("PimpYourBlech_Data.Models.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("OrderId"));

                    b.Property<int>("CustomerId")
                        .HasColumnType("integer");

                    b.Property<int>("DeliveryAddressId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PaymentValueId")
                        .HasColumnType("integer");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("numeric");

                    b.HasKey("OrderId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("DeliveryAddressId");

                    b.HasIndex("PaymentValueId");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            OrderId = 1,
                            CustomerId = 1,
                            DeliveryAddressId = 1,
                            OrderDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            PaymentValueId = 1,
                            TotalPrice = 2000m
                        });
                });

            modelBuilder.Entity("PimpYourBlech_Data.Models.OrderPosition", b =>
                {
                    b.Property<int>("OrderPositionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("OrderPositionId"));

                    b.Property<string>("ArticleNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("OrderId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("numeric");

                    b.HasKey("OrderPositionId");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderPositions");

                    b.HasData(
                        new
                        {
                            OrderPositionId = 1,
                            ArticleNumber = "100000",
                            Brand = "Volkswagen",
                            Name = "Queenstown Felge",
                            OrderId = 1,
                            Quantity = 2,
                            Type = 1,
                            UnitPrice = 1000m
                        });
                });

            modelBuilder.Entity("PimpYourBlech_Data.Models.PaymentValue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AccountOwner")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Bic")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("CustomerId")
                        .HasColumnType("integer");

                    b.Property<string>("Iban")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("PaymentValues");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccountOwner = "Max Mustermann",
                            Bic = "INGDDEFFXXX",
                            CustomerId = 1,
                            Iban = "DE44500105175407324931"
                        });
                });

            modelBuilder.Entity("PimpYourBlech_Data.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ProductId"));

                    b.Property<string>("ArticleNumber")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("CarId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<int>("ProductType")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("ProductId");

                    b.HasIndex("ArticleNumber")
                        .IsUnique();

                    b.HasIndex("CarId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            ArticleNumber = "100000",
                            Brand = "Volkswagen",
                            CarId = 1,
                            Description = "Sportliche Alufelge mit roten Akzenten.",
                            Name = "Queenstown Felge",
                            Price = 1000m,
                            ProductType = 1,
                            Quantity = 10
                        },
                        new
                        {
                            ProductId = 2,
                            ArticleNumber = "100001",
                            Brand = "Volkswagen",
                            CarId = 1,
                            Description = "Aerodynamische Premium-Felge für sportliche Fahrweise.",
                            Name = "Warmenau Performance Felge",
                            Price = 1200m,
                            ProductType = 1,
                            Quantity = 10
                        },
                        new
                        {
                            ProductId = 21,
                            ArticleNumber = "100011",
                            Brand = "Volkswagen",
                            CarId = 1,
                            Description = "Leichte Schmiedefelge mit hoher Stabilität.",
                            Name = "Pretoria Sport Felge",
                            Price = 1350m,
                            ProductType = 1,
                            Quantity = 8
                        },
                        new
                        {
                            ProductId = 3,
                            ArticleNumber = "100002",
                            Brand = "Volkswagen",
                            CarId = 1,
                            Description = "325 PS Turbo-Benzinmotor.",
                            Name = "GTI 2.0 TFSI Performance Motor",
                            Price = 2500m,
                            ProductType = 0,
                            Quantity = 5
                        },
                        new
                        {
                            ProductId = 4,
                            ArticleNumber = "100003",
                            Brand = "Volkswagen",
                            CarId = 1,
                            Description = "Hochleistungsmotor mit Rennsportabstimmung.",
                            Name = "GTI Clubsport RS Motor",
                            Price = 3400m,
                            ProductType = 0,
                            Quantity = 3
                        },
                        new
                        {
                            ProductId = 15,
                            ArticleNumber = "100008",
                            Brand = "Volkswagen",
                            CarId = 1,
                            Description = "Effizienter Hybridmotor mit ruhigem Lauf.",
                            Name = "GTI EcoBoost Hybrid Motor",
                            Price = 3900m,
                            ProductType = 0,
                            Quantity = 4
                        },
                        new
                        {
                            ProductId = 5,
                            ArticleNumber = "100004",
                            Brand = "Volkswagen",
                            CarId = 1,
                            Description = "Adaptive Matrix-LED-Scheinwerfer.",
                            Name = "IQ.Light LED Matrix Pro",
                            Price = 1450m,
                            ProductType = 2,
                            Quantity = 10
                        },
                        new
                        {
                            ProductId = 6,
                            ArticleNumber = "100007",
                            Brand = "Volkswagen",
                            CarId = 1,
                            Description = "Sportlicher LED-Scheinwerfer mit dunklem Gehäuse.",
                            Name = "Dynamic Vision LED Blackline",
                            Price = 1580m,
                            ProductType = 2,
                            Quantity = 8
                        },
                        new
                        {
                            ProductId = 16,
                            ArticleNumber = "100009",
                            Brand = "Volkswagen",
                            CarId = 1,
                            Description = "Extrem helle LED-Scheinwerfer für maximale Sicht.",
                            Name = "NightDrive LED UltraBeam",
                            Price = 1750m,
                            ProductType = 2,
                            Quantity = 6
                        },
                        new
                        {
                            ProductId = 7,
                            ArticleNumber = "100005",
                            Brand = "Volkswagen",
                            CarId = 1,
                            Description = "Kräftige Sportlackierung.",
                            Name = "Tornadorot",
                            Price = 1800m,
                            ProductType = 4,
                            Quantity = 20
                        },
                        new
                        {
                            ProductId = 8,
                            ArticleNumber = "100006",
                            Brand = "Volkswagen",
                            CarId = 1,
                            Description = "Eleganter Perlglanz.",
                            Name = "Metallic Weiß Perleffekt",
                            Price = 1900m,
                            ProductType = 4,
                            Quantity = 20
                        },
                        new
                        {
                            ProductId = 17,
                            ArticleNumber = "100010",
                            Brand = "Volkswagen",
                            CarId = 1,
                            Description = "Tiefschwarze Premium-Lackierung.",
                            Name = "Deep Black Pearl",
                            Price = 2100m,
                            ProductType = 4,
                            Quantity = 15
                        },
                        new
                        {
                            ProductId = 22,
                            ArticleNumber = "200010",
                            Brand = "Volkswagen",
                            CarId = 2,
                            Description = "Klassische Alufelge für Alltag und Komfort.",
                            Name = "Astana Felge",
                            Price = 850m,
                            ProductType = 1,
                            Quantity = 12
                        },
                        new
                        {
                            ProductId = 23,
                            ArticleNumber = "200011",
                            Brand = "Volkswagen",
                            CarId = 2,
                            Description = "Sportliche Mehrspeichenfelge.",
                            Name = "Bergamo Sport Felge",
                            Price = 980m,
                            ProductType = 1,
                            Quantity = 10
                        },
                        new
                        {
                            ProductId = 24,
                            ArticleNumber = "200012",
                            Brand = "Volkswagen",
                            CarId = 2,
                            Description = "Schwarze Performance-Felge.",
                            Name = "Verona Black Performance Felge",
                            Price = 1100m,
                            ProductType = 1,
                            Quantity = 6
                        },
                        new
                        {
                            ProductId = 11,
                            ArticleNumber = "200003",
                            Brand = "Volkswagen",
                            CarId = 2,
                            Description = "Effizienter Stadtturbomotor.",
                            Name = "Polo 1.0 TSI BlueMotion Motor",
                            Price = 1800m,
                            ProductType = 0,
                            Quantity = 8
                        },
                        new
                        {
                            ProductId = 12,
                            ArticleNumber = "200004",
                            Brand = "Volkswagen",
                            CarId = 2,
                            Description = "Sportlicher Turbomotor.",
                            Name = "Polo 1.5 TSI GT-Line Motor",
                            Price = 2400m,
                            ProductType = 0,
                            Quantity = 6
                        },
                        new
                        {
                            ProductId = 19,
                            ArticleNumber = "200008",
                            Brand = "Volkswagen",
                            CarId = 2,
                            Description = "Hybridantrieb mit niedrigem Verbrauch.",
                            Name = "Polo 1.2 Hybrid Drive",
                            Price = 2600m,
                            ProductType = 0,
                            Quantity = 5
                        },
                        new
                        {
                            ProductId = 13,
                            ArticleNumber = "200005",
                            Brand = "Volkswagen",
                            CarId = 2,
                            Description = "Gleichmäßige LED-Ausleuchtung.",
                            Name = "Polo LED Comfort Beam",
                            Price = 980m,
                            ProductType = 2,
                            Quantity = 10
                        },
                        new
                        {
                            ProductId = 14,
                            ArticleNumber = "200006",
                            Brand = "Volkswagen",
                            CarId = 2,
                            Description = "Erweiterte Reichweite bei Nacht.",
                            Name = "Polo LED NightVision Plus",
                            Price = 1150m,
                            ProductType = 2,
                            Quantity = 8
                        },
                        new
                        {
                            ProductId = 20,
                            ArticleNumber = "200009",
                            Brand = "Volkswagen",
                            CarId = 2,
                            Description = "Blendfreies Fernlicht mit Pixel-Technologie.",
                            Name = "Polo Adaptive Pixel Light",
                            Price = 1350m,
                            ProductType = 2,
                            Quantity = 6
                        },
                        new
                        {
                            ProductId = 9,
                            ArticleNumber = "200001",
                            Brand = "Volkswagen",
                            CarId = 2,
                            Description = "Kühle Metallic-Lackierung.",
                            Name = "Crystal Ice Blue Metallic",
                            Price = 1600m,
                            ProductType = 4,
                            Quantity = 20
                        },
                        new
                        {
                            ProductId = 10,
                            ArticleNumber = "200002",
                            Brand = "Volkswagen",
                            CarId = 2,
                            Description = "Edler Rotton mit Tiefenglanz.",
                            Name = "Kings Red Velvet",
                            Price = 1700m,
                            ProductType = 4,
                            Quantity = 20
                        },
                        new
                        {
                            ProductId = 18,
                            ArticleNumber = "200007",
                            Brand = "Volkswagen",
                            CarId = 2,
                            Description = "Moderne urbane Graulackierung.",
                            Name = "Urban Grey Metallic",
                            Price = 1650m,
                            ProductType = 4,
                            Quantity = 18
                        },
                        new
                        {
                            ProductId = 30,
                            ArticleNumber = "300001",
                            Brand = "Volkswagen",
                            CarId = 1,
                            Description = "Sportlicher Carbon-Heckspoiler für verbesserte Aerodynamik.",
                            Name = "GTI Carbon Heckspoiler",
                            Price = 950m,
                            ProductType = 17,
                            Quantity = 5
                        },
                        new
                        {
                            ProductId = 31,
                            ArticleNumber = "300002",
                            Brand = "Volkswagen",
                            CarId = 2,
                            Description = "Kompakter Sportspoiler für den Polo.",
                            Name = "Polo Sport Heckspoiler",
                            Price = 720m,
                            ProductType = 17,
                            Quantity = 7
                        });
                });

            modelBuilder.Entity("PimpYourBlech_Data.Models.RimDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("DiameterInInch")
                        .HasColumnType("numeric");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<decimal>("WidthInInch")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("ProductId")
                        .IsUnique();

                    b.ToTable("Rims");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DiameterInInch = 19m,
                            ProductId = 1,
                            WidthInInch = 8m
                        },
                        new
                        {
                            Id = 2,
                            DiameterInInch = 20m,
                            ProductId = 2,
                            WidthInInch = 8.5m
                        },
                        new
                        {
                            Id = 3,
                            DiameterInInch = 18m,
                            ProductId = 21,
                            WidthInInch = 7.5m
                        },
                        new
                        {
                            Id = 4,
                            DiameterInInch = 16m,
                            ProductId = 22,
                            WidthInInch = 6.5m
                        },
                        new
                        {
                            Id = 5,
                            DiameterInInch = 17m,
                            ProductId = 23,
                            WidthInInch = 7.0m
                        },
                        new
                        {
                            Id = 6,
                            DiameterInInch = 18m,
                            ProductId = 24,
                            WidthInInch = 7.5m
                        });
                });

            modelBuilder.Entity("ConfigurationProduct", b =>
                {
                    b.HasOne("PimpYourBlech_Data.Models.Configuration", null)
                        .WithMany()
                        .HasForeignKey("ConfigurationsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PimpYourBlech_Data.Models.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductsProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PimpYourBlech_Data.Models.ColorDetail", b =>
                {
                    b.HasOne("PimpYourBlech_Data.Models.Product", "Product")
                        .WithOne("ColorDetail")
                        .HasForeignKey("PimpYourBlech_Data.Models.ColorDetail", "ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("PimpYourBlech_Data.Models.CommunityAnswer", b =>
                {
                    b.HasOne("PimpYourBlech_Data.Models.CommunityQuestion", "Question")
                        .WithMany("Answers")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("PimpYourBlech_Data.Models.Configuration", b =>
                {
                    b.HasOne("PimpYourBlech_Data.Models.Car", "Car")
                        .WithMany()
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PimpYourBlech_Data.Models.Customer", "Customer")
                        .WithMany("Configurations")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Car");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("PimpYourBlech_Data.Models.DeliveryAddress", b =>
                {
                    b.HasOne("PimpYourBlech_Data.Models.Customer", "Customer")
                        .WithMany("DeliveryAddresses")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("PimpYourBlech_Data.Models.EngineDetail", b =>
                {
                    b.HasOne("PimpYourBlech_Data.Models.Product", "Product")
                        .WithOne("EngineDetail")
                        .HasForeignKey("PimpYourBlech_Data.Models.EngineDetail", "ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("PimpYourBlech_Data.Models.LightsDetail", b =>
                {
                    b.HasOne("PimpYourBlech_Data.Models.Product", "Product")
                        .WithOne("LightsDetail")
                        .HasForeignKey("PimpYourBlech_Data.Models.LightsDetail", "ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("PimpYourBlech_Data.Models.Order", b =>
                {
                    b.HasOne("PimpYourBlech_Data.Models.Customer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PimpYourBlech_Data.Models.DeliveryAddress", "DeliveryAddress")
                        .WithMany()
                        .HasForeignKey("DeliveryAddressId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PimpYourBlech_Data.Models.PaymentValue", "PaymentValue")
                        .WithMany()
                        .HasForeignKey("PaymentValueId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("DeliveryAddress");

                    b.Navigation("PaymentValue");
                });

            modelBuilder.Entity("PimpYourBlech_Data.Models.OrderPosition", b =>
                {
                    b.HasOne("PimpYourBlech_Data.Models.Order", "Order")
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("PimpYourBlech_Data.Models.PaymentValue", b =>
                {
                    b.HasOne("PimpYourBlech_Data.Models.Customer", "Customer")
                        .WithMany("PaymentValues")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("PimpYourBlech_Data.Models.Product", b =>
                {
                    b.HasOne("PimpYourBlech_Data.Models.Car", "Car")
                        .WithMany("Products")
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Car");
                });

            modelBuilder.Entity("PimpYourBlech_Data.Models.RimDetail", b =>
                {
                    b.HasOne("PimpYourBlech_Data.Models.Product", "Product")
                        .WithOne("RimDetail")
                        .HasForeignKey("PimpYourBlech_Data.Models.RimDetail", "ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("PimpYourBlech_Data.Models.Car", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("PimpYourBlech_Data.Models.CommunityQuestion", b =>
                {
                    b.Navigation("Answers");
                });

            modelBuilder.Entity("PimpYourBlech_Data.Models.Customer", b =>
                {
                    b.Navigation("Configurations");

                    b.Navigation("DeliveryAddresses");

                    b.Navigation("Orders");

                    b.Navigation("PaymentValues");
                });

            modelBuilder.Entity("PimpYourBlech_Data.Models.Order", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("PimpYourBlech_Data.Models.Product", b =>
                {
                    b.Navigation("ColorDetail");

                    b.Navigation("EngineDetail");

                    b.Navigation("LightsDetail");

                    b.Navigation("RimDetail");
                });
#pragma warning restore 612, 618
        }
    }
}
